build:
  image: jvican/scala-sbt-git
  volumes:
    - /platform:/drone/.gnupg
  environment:
    - GITHUB_PLATFORM_TEST_TOKEN=$$GITHUB_PLATFORM_TEST_TOKEN
    - PLATFORM_PGP_PASSPHRASE=$$PLATFORM_PGP_PASSPHRASE
    - BINTRAY_USERNAME=$$BINTRAY_USERNAME
    - BINTRAY_PASSWORD=$$BINTRAY_PASSWORD
  commands:
    - ./bin/store_credentials.sh $BINTRAY_USERNAME $BINTRAY_PASSWORD
    - test -e "/drone/.sbt" && mv /drone/.sbt $HOME/.sbt
    - git config --global user.email "lucky@luke.com"
    - git config --global user.name "Lucky Luke, the Cowboy"
    - export COURSIER_CACHE="/drone/.coursier-cache"
    - sbt clean test sbt-platform/clean sbt-platform/test sbt-platform/publishLocal sbt-platform/scripted -Dsbt.ivy.home=/drone/.ivy2
    - mv $HOME/.sbt /drone/.sbt

cache:
  mount:
    - .git
    - /drone/.ivy2
    - /drone/.coursier-cache
    - /drone/.sbt
