pipeline:
  build:
    image: scalaplatform/scala:0.5
    volumes:
      - /platform:/keys
    commands:
      - sbt clean test sbt-platform/clean sbt-platform/test sbt-platform/publishLocal sbt-platform/scripted
      - sbt process/publishProcessAndDocs
