build:
  image: jvican/scala-sbt-git
  pull: true
  volumes:
    - /platform:/keys
  environment:
    - GITHUB_PLATFORM_TOKEN=$$GITHUB_PLATFORM_TEST_TOKEN
    - PLATFORM_PGP_PASSPHRASE=$$PLATFORM_PGP_PASSPHRASE
    - BINTRAY_USERNAME=$$BINTRAY_USERNAME
    - BINTRAY_PASSWORD=$$BINTRAY_PASSWORD
  commands:
    - sbt clean test sbt-platform/clean sbt-platform/test sbt-platform/publishLocal sbt-platform/scripted
    - sbt process/publishProcess docs/publishMicrosite

cache:
  mount:
    - .git
    - /drone/.ivy2
    - /drone/.coursier-cache
    - /drone/.sbt
