build:
  image: joshdev/alpine-sbt
  commands:
    - cp -R /drone/.sbt $HOME/.sbt
    - sbt clean test sbt-utils/clean sbt-utils/test -Dsbt.ivy.home=/drone/.ivy2
    - cp -R $HOME/.sbt /drone/.sbt  

cache:
  mount:
    - .git
    - /drone/.ivy2
    - /drone/.sbt
