workspace:
  base: /drone

pipeline:
  build:
    image: scalaplatform/scala
    commands:
      - sbt clean test sbt-platform/clean sbt-platform/test sbt-platform/publishLocal sbt-platform/scripted
      - sbt process/publishProcessAndDocs
