build:
  image: joshdev/alpine-sbt
  commands:
    - mv /drone/.sbt $HOME/.sbt
    - mv /drone/.coursier $HOME/.coursier
    - sbt clean test sbt-utils/clean sbt-utils/test -Dsbt.ivy.home=/drone/.ivy2
    - mv $HOME/.coursier /drone/.coursier
    - mv $HOME/.sbt /drone/.sbt

cache:
  mount:
    - .git
    - /drone/.ivy2
    - /drone/.coursier
    - /drone/.sbt
