build:
  image: jvican/docker-alpine-sbt-git
  environment:
    - GITHUB_PLATFORM_TEST_TOKEN=$$GITHUB_PLATFORM_TEST_TOKEN
  commands:
    - test -e "/drone/.sbt" && mv /drone/.sbt $HOME/.sbt
    - export COURSIER_CACHE="/drone/.coursier-cache"
    - sbt clean test sbt-platform/clean sbt-platform/test sbt-platform/publishLocal sbt-platform/scripted -Dsbt.ivy.home=/drone/.ivy2
    - mv $HOME/.sbt /drone/.sbt 

cache:
  mount:
    - .git
    - /drone/.ivy2
    - /drone/.coursier-cache
    - /drone/.sbt
